default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: greeting_app_development

test:
  <<: *default
  database: greeting_app_test

production:
  <<: *default
  database: greeting_app_production
  password: <%= ENV['GREETING_APP_DATABASE_PASSWORD'] %>